import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

import ConvexClientProvider from "./components/ConvexClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shredded Edge Arbitrage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="flex items-center p-4 shadow-md shadow-sky-300 rounded-b-xl bg-sky-200">
            <Link href="/">
              <h1 className="text-2xl font-bold">Home</h1>
            </Link>
            <Link href="/Soccer">
              <h1 className="text-2xl ml-4">Soccer</h1>
            </Link>
            <Link href="/NBA">
              <h1 className="text-2xl ml-4">NBA</h1>
            </Link>
            <Link href="/NFL">
              <h1 className="text-2xl ml-4">NFL</h1>
            </Link>
          </header>
          {children}
        </body>
      </html>
    </ConvexClientProvider>
  );
}
